### ISSUE TITLE
Problem with LeaderBoard Position + Mass 

### ISSUE THREAD

**Issue by Jhair2015** [Tyler3D/Multi-Ogar-Edited-Unlimited-Plugins#2]
i have your plugins, and leaderboard position + mass it affects to self position on my client

http://shairplus.tk/   try u with a localhost

**Comment by plazo123** [comment]
hi there 
is http://shairplus.tk/ your own game client because i love it and i want to ask 
that maby i could get the files for the game because i love a game like that and i want the dowload for the web site i would realy thank you for that ::)   :) 

plazo
..

**Comment by Logan7432** [comment]
any fix yet?

**Comment by Tyler3D** [comment]
This is a known bug
