### ISSUE TITLE
how do i set auto restart time 

### ISSUE THREAD

**Issue by plazo123** [Tyler3D/Multi-Ogar-Edited-Unlimited-Plugins#3]
thx

**Comment by Jhair2015** [comment]
@plazo123  https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited-Plugins/blob/master/AutoRestart.js#L11

`    this.restartInterval = 24 * 3600000`

//Is the time that is multiplied by the milliseconds, convert milliseconds to hours or minutes and multiply that by 1 instead of 24 lol
